version: "3"
services:
  app:
    build: .
    restart: always
    depends_on:
      - "db"
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: pass
      TZ: Asia/Tokyo
    volumes:
      - ./volume:/var/lib/mysql
      - C:\Users\suwau\OneDrive\デスクトップ\Tool\Bot\TaskManager\initdb.d:/docker-entrypoint-initdb.d
