version: "3"
services:
  app:
    build: .
    restart: always
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - "db"
  db:
    image: mariadb:11.3.2
    environment:
      MARIADB_DATABASE: task_manager
      MARIADB_ROOT_PASSWORD: pass
      TZ: Asia/Tokyo
    volumes:
      - ./volume:/var/lib/mysql
      - C:\Users\suwau\OneDrive\デスクトップ\Tool\Bot\TaskManager\initdb.d:/docker-entrypoint-initdb.d
