version: "3"
services:
  app:
    build: .
    restart: always
    depends_on:
      - "db"
  db:
    image: mariadb:11.3.2
    environment:
      MARIADB_DATABASE: task_manaer
      MARIADB_ROOT_PASSWORD: pass
    volumes:
      - ./volume:/var/lib/mysql
